### ISSUE TITLE
Support viewing account summary on networks without NEAR Social contract

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#301]
It was originally reported by statelessnet participants, but there is a reproduction config:

```toml
[network_connection.mainnet-broken-test]
network_name = "mainnet2"
rpc_url = "https://rpc.mainnet.near.org/"
wallet_url = "https://app.mynearwallet.com/"
explorer_transaction_url = "https://explorer.near.org/transactions/"
```

(notice that `network_name` has to be different from mainnet/testnet to reproduce the issue as we have fallback values for those networks)

<img width="1125" alt="image" src="https://github.com/near/near-cli-rs/assets/304265/bb455431-beb9-4181-ac1f-74ae08bdba12">

The command should not fail!
